### PR TITLE
Update master from source

### PR DESCRIPTION
**Pull request by coyotegrey**
# Submission Checklist
## Required

- [ ] The pull request title clearly contains the name of the sheet I am editing.
- [ ] The pull request title clearly states the type of change I am submitting (New Sheet/New Feature/Bugfix/etc.).
- [ ] The pull request makes changes to files in only one sub-folder.
- [ ] The pull request does not contain changes to any json files in the translations folder (translation.json is permitted)

## New Sheet Details

- The name of this game is: <   >  _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The publisher of this game is: <   > _(i.e. Wizards of the Coast, Evil Hat)_
- The name of this game system/family is: <   > _(i.e. Dungeons & Dragons, FATE)_

- [ ] I have followed the [Character Sheets Standards](https://wiki.roll20.net/Building_Character_Sheets#Roll20_Character_Sheets_Repository) when building this sheet.

- [ ] This sheet has been made on behalf of, or by, the game's publisher.
- [ ] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [ ] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

# Changes / Description

### CODE REVIEW

**Comment by veratulmp** [comment]
Did you need any help with the Fallout sheet? I noticed that some changes are needed to make the roll templates look good in dark mode.

**Comment by coyotegrey** [comment]
Working on adding translation support right now if you want to test it. I'll have to take a look at dark mode. :/

**Comment by coyotegrey** [comment]
I added an update for the rolltemplates to the next version. The sheet seems pretty extensive. Looks the same right now, just not great on the dark background. If I have time, I've been thinking about doing a pipboy style that would probably look better with dark mode.

**Comment by veratulmp** [comment]
Yeah, the sheet itself seemed to be readable in dark mode before, just the number colors/background on the roll templates that didn't. Thanks for taking a look at that.

I had to do the same dark mode updates recently for my World Wide Wrestling RPG 2nd Ed sheet. I've already done the translation support for it, wasn't difficult but it was certainly time consuming.

**Pull request merged**
